# Site settings
#permalink: /blog/:categories/:title
title: Jason Mitchell
email: contact@jason-mitchell.com
description: > 
  Irish software developer in Yorkshire.  Amateur Domain Driven Designer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://json.codes" # the base hostname & protocol for your site
twitter_username: jmitch18
github_username:  jasonmitchell

# Build settings
markdown: kramdown
permalink: /blog/:categories/:title/
paginate: 10
paginate_path: "/blog/page:num/"
gems:
- jemoji
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist
