# Site settings
#permalink: /blog/:categories/:title
title: Jason Mitchell
email: contact@jason-mitchell.com
description: > # this means to ignore newlines until "baseurl:"
  I write code.  I care about quality. I love to learn.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://json.codes" # the base hostname & protocol for your site
twitter_username: jmitch18
github_username:  jasonmitchell

# Build settings
markdown: kramdown
permalink: /blog/:categories/:title
paginate: 5
paginate_path: "/blog/page:num/"
